### PR TITLE
Add 386 (intel 32bit) target to Makefile

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by martialblog** [comment]
Should also be added to the goreleaser config if releases should contain this target.

**Comment by RincewindsHat** [comment]
Indeed. forgot that.

**Comment by martialblog** [comment]
Just my curiosity, any particular reason for adding 386? Or just why not?

**Review by martialblog — APPROVED** [review]

**Comment by RincewindsHat** [comment]
https://www.netways.de/blog/2024/01/19/check-system-basics/#comments
Latest comment :-)

**Pull request merged**
